"""add fields trip creator

Revision ID: 840773f46984
Revises: 987d3cba29f9
Create Date: 2026-04-09 17:06:19.475831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '840773f46984'
down_revision: Union[str, Sequence[str], None] = '987d3cba29f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'trip', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.drop_column('trip', 'creator_id')
    # ### end Alembic commands ###
